version: '3'

services:
  back_end:
    container_name: back_end
    tty: true
    build:
      context: .
      dockerfile: .docker/back_end.DockerFile
    ports: 
      - 3000:3000
    volumes:
      - ./back_end:/app
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mongo-express
    command: > 
      bash -c "npm install && npm run start"
    networks:
      - api-network
  
  cms:
    container_name: cms
    tty: true
    build:
      context: .
      dockerfile: .docker/cms.DockerFile
    ports:
      - 3001:3001
    command: > 
      bash -c "npm install && npm run dev"
    volumes:
      - ./cms:/app
    environment:
      PORT: 3001
    networks:
      - api-network
    
  boilerplate-mongo:
    container_name: boilerplate-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_ROOT_DATABASE: ${DB_NAME}
    volumes:
      - ./.database:/data/db
    ports:
      - 27017:27017
    networks:
      - api-network

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8888:8081
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: boilerplate-mongo
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
  #     ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
  #   networks:
  #     - api-network
  #   links:
  #     - boilerplate-mongo

  web:
    container_name: web
    build:
      context: .
      dockerfile: .docker/web.DockerFile
    ports:
      - 8080:80
    volumes: 
      - ./web/:/web
    tty: true
    environment: 
      - TZ=Asia/HoChiMinh
    networks:
      - api-network

  # smart_contract:
  #   container_name: smart_contract
  #   build:
  #     context: .
  #     dockerfile: .docker/smart_contract.DockerFile
  #   ports:
  #     - 8545:8545
  #   volumes: 
  #     - ./smart_contract:/smart_contract
  #   tty: true
  #   environment: 
  #     - TZ=Asia/HoChiMinh
  #   networks:
  #     - api-network

networks:
  api-network:
     driver: bridge
